group 'org.xrstudio.xmpp'
version '1.0'

buildscript {
    ext {
        agp_version = '8.3.1'
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "com.android.tools.build:gradle:$agp_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {

    namespace "org.xrstudio.xmpp"

    defaultConfig {
        compileSdk 33
        minSdkVersion 26 //16
        multiDexEnabled true
    }
}

configurations {
    all*.exclude group: 'xpp3', module: 'xpp3'
    all*.exclude group: 'net.sf.kxml', module: 'kxml2'
    all*.exclude group: 'xmlpull', module: 'xmlpull'
}

ext {
    // smackVersion = '4.3.4'
    //smackVersion = '4.4.6'
    smackVersion = '4.4.8'
}


dependencies {
    implementation "org.igniterealtime.smack:smack-tcp:$smackVersion"
    implementation "org.igniterealtime.smack:smack-experimental:$smackVersion"
    implementation "org.igniterealtime.smack:smack-android:$smackVersion"
    implementation "org.igniterealtime.smack:smack-im:$smackVersion"
    implementation "org.igniterealtime.smack:smack-extensions:$smackVersion"
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.amazonaws:aws-android-sdk-core:2.73.0'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.20.1'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.73.0'
    implementation 'com.amazonaws:aws-android-sdk-ddb:2.73.0'
    implementation 'com.android.support:multidex:1.0.3'
    //implementation fileTree(dir: 'E:\\Apk\\version de flutter\\flutter_windows_3.7.8-stable_dart_2.19.5\\flutter\\bin\\cache\\artifacts\\engine\\android-x64', include: ['*.aar', '*.jar'], exclude: [])
}